### ISSUE TITLE
BtcTransaction.fromRaw Fails with `RangeError`

### ISSUE THREAD

**Issue by x32134** [MohsenHaydari/bitcoin_base#9]
#### Description
When attempting to parse the following transaction using `BtcTransaction.fromRaw`, the function throws a `RangeError`:

- **Raw Transaction**:
`020000000001014385e53a8edf48ce63bb8ffd96a05484d66f25e03afe700bd1f997334295161c0100000000fdffffff020000000000000000096a5d061601140114003c0f000000000000225120520ad38d69a261cfaadd3e1d42be7b5b7c59a8741988fce9850c1fbd1934a472014039ca78785e9976cf1255cbe560006764e01f1440066a977783fb6a01b9c2e5c609423fa720a3064022cd7184c84eb01177916179c9bd85ef63c0d47ab7af992200000000`

- **Transaction ID**: `0677ba8ee9973bd76c4b6f44e811c1973333279fbf7966c75a1fbc57f0e65871`

#### Error Details
The call to `BtcTransaction.fromRaw(rawTx)` results in the following error:
`RangeError (end): Invalid value: Not in inclusive range 2..9: 11`

**Comment by mrtnetwork** [comment]
> ### Issue: `BtcTransaction.fromRaw` Fails with `RangeError`
> #### Description
> When attempting to parse the following transaction using `BtcTransaction.fromRaw`, the function throws a `RangeError`:
> 
> * **Raw Transaction**:
>   `020000000001014385e53a8edf48ce63bb8ffd96a05484d66f25e03afe700bd1f997334295161c0100000000fdffffff020000000000000000096a5d061601140114003c0f000000000000225120520ad38d69a261cfaadd3e1d42be7b5b7c59a8741988fce9850c1fbd1934a472014039ca78785e9976cf1255cbe560006764e01f1440066a977783fb6a01b9c2e5c609423fa720a3064022cd7184c84eb01177916179c9bd85ef63c0d47ab7af992200000000`
> * **Transaction ID**: `0677ba8ee9973bd76c4b6f44e811c1973333279fbf7966c75a1fbc57f0e65871`
> 
> #### Error Details
> The call to `BtcTransaction.fromRaw(rawTx)` results in the following error: `RangeError (end): Invalid value: Not in inclusive range 2..9: 11`

Thank you for reporting that. I've updated the package—please update to version [4.9.1](https://pub.dev/packages/bitcoin_base).
